### ISSUE TITLE
Make resource limit configurable

### ISSUE THREAD

**Issue by cgawron** [fhswf/jupyterhub#38]
The resource limits in `jupyterhub_config.py` should not be hard-coded.

A simple FashionMNIST sample network breaks with only 10G of RAM. The limits regarding CPU cores and memory should be configurable either 

- via environment variables
- per Moodle environment

to allow appropriate configuration for different classes.

**Comment by zozoxo1** [comment]
with pr #52 this issue should be resolved temporarily. still need to make it configurable per moodle env.
