### ISSUE TITLE
Logout / Login loop

### ISSUE THREAD

**Issue by zozoxo1** [fhswf/jupyterhub#58]
Reproduce:
- Login to Keycloak / SSO
- Get redirected to jupyterhub
- Logout from Jupyterhub

What will happen:
- You get redirected to keycloak which will redirect you back to jupyterhub logged in

What should happen:
- You get redirected to keycloak where you can login

**Comment by zozoxo1** [comment]
can be fixed by adding logout url for keycloak in jupyterhub config

**Comment by zozoxo1** [comment]
client_id=<my_client_id> and refresh_token=<refresh_token> has to be provided in request for logout

**Comment by DeepCowProductions** [comment]
As we now use k8s, this issue is no longer relevant
